### ISSUE TITLE
Cant raise after my first turn

### ISSUE THREAD

**Issue by joeydebreuk** [dickreuter/neuron_poker#13]
**Describe the bug**
The following is currently not possible:
Player 1 bets -> Player 2 raises -> Player 1 raises
And: 
Player 1 checks -> Player 2 raises -> Player 1 raises

**To Reproduce**
1. Add one `KeyPressAgent` instead of a `RandomPlayer` in the method `random_agents` in `main.py`
2. run `main.py random --render`

The simulation:
3. Bet in your turn
4. Opponents raises
5. Your options are only `CALL` and `FOLD`

**Expected behaviour**
Player 1 can raise

**Additional context**
I am not sure if you would expect issues adding a `KeyPressAgent` to the random simulation. Looking at the code it looks like it shouldn't be a problem. Also, looking at the random simulation without adding a `KeyPressAgent`, I dont see players raising twice.

log:

INFO - ===ROUND: Stage.RIVER ===
Choose action with number: [<Action.CHECK: 1>, <Action.RAISE_3BB: 3>, <Action.RAISE_3BB: 3>, <Action.RAISE_POT: 4>, <Action.RAISE_2POT: 5>, <Action.ALL_IN: 6>]
3
INFO - Seat 0 (Keypress): Action.RAISE_3BB - Remaining stack: 641, Round pot: 6, Community pot: 174, player pot: 6
INFO - Seat 1 (Random): Action.CALL - Remaining stack: 459, Round pot: 12, Community pot: 174, player pot: 6
Choose action with number: [<Action.CALL: 2>, <Action.FOLD: 0>]

**Comment by dickreuter** [comment]
Is this about not being able to Re-raise or not being able to raise at all? Should there be a limit until when it’s possible to raise?

**Comment by joeydebreuk** [comment]
"Is this about not being able to Re-raise or not being able to raise at all?"
-  about not being able to Re-raise.  

"Should there be a limit until when it’s possible to raise?"
- IMO the current way of raising with the different raising options is ok

**Comment by dickreuter** [comment]
But should a reraise be possible indefinitely? At the moment it’s capped to 2 rounds max.

**Comment by dickreuter** [comment]
Added a parameter in the env that can be increased to 9999. That should solve the problem.
https://github.com/dickreuter/neuron_poker/pull/14
