### ISSUE TITLE
6 random players playing against each other uses A LOT of ram

### ISSUE THREAD

**Issue by haralEcl** [dickreuter/neuron_poker#15]
**Describe the bug**
This is not really a bug, it's more of a question. Why is only playing with random players uses such a big amount of ram?
It's expected that the ram consumption increases as more hands are being played (to save log and stuff in memory). But I am talking about 3-4GB of ram after only ~20 hands.

**To Reproduce**
Follow the installation steps. (The readme is quite clear, it very helpful thank you !)
Then run: python main.py random --render

**Expected behavior**
I would except the ram to be used less, as hands are being played.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/16225570/62897796-34aa7680-bd54-11e9-8910-31f271e2ff93.JPG)

**Additional context**
I have only 8gb of ram

**Comment by dickreuter** [comment]
Is there any difference if you don't use --render?

**Comment by haralEcl** [comment]
Indeed, without the render the memory usage is stable.
So the issue comes from pyglet ?
