### ISSUE TITLE
TypeError: len is not well defined for symbolic Tensors. (dense_4/BiasAdd:0)

### ISSUE THREAD

**Issue by franzman007** [dickreuter/neuron_poker#22]
Hello together,
i have some problems with the following run

python main.py dqn_train

Exception:
(base) franzman007:neuron_poker-master franzman007$ python main.py dqn_train
/Users/franzman007/opt/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/franzman007/opt/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/franzman007/opt/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/franzman007/opt/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/franzman007/opt/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/franzman007/opt/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using TensorFlow backend.
Using default log file
Saving log file to: /Users/franzman007/Downloads/neuron_poker-master/log/default.log
Saving info file to: /Users/franzman007/Downloads/neuron_poker-master/log/default_info.log
Saving error only file to: /Users/franzman007/Downloads/neuron_poker-master/log/default_errors.log
Screenloglevel: 20
INFO - Initializing program
INFO - 
INFO - ++++++++++++++++++
INFO - Starting new hand.
INFO - ++++++++++++++++++
INFO - Dealer is at position 0
INFO - Player 0 got ['KD', '2H'] and $100
INFO - Player 1 got ['9D', 'JC'] and $100
INFO - Player 2 got ['QD', '6H'] and $100
INFO - Player 3 got ['7D', 'AD'] and $100
INFO - Player 4 got ['8D', 'JS'] and $100
INFO - Player 5 got ['JH', '4H'] and $100
INFO - 
INFO - ===Round: Stage: PREFLOP
INFO - Seat 1 (equity/20/30): Action.SMALL_BLIND - Remaining stack: 99, Round pot: 1, Community pot: 0, player pot: 1
INFO - Seat 2 (Random): Action.BIG_BLIND - Remaining stack: 98, Round pot: 3, Community pot: 0, player pot: 2
INFO - Seat 3 (Random): Action.FOLD - Remaining stack: 100, Round pot: 3, Community pot: 0, player pot: 0
INFO - Seat 4 (Random): Action.RAISE_POT - Remaining stack: 97, Round pot: 6, Community pot: 0, player pot: 3
WARNING:tensorflow:From /Users/franzman007/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING - From /Users/franzman007/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Traceback (most recent call last):
  File "main.py", line 210, in <module>
    command_line_parser()
  File "main.py", line 70, in command_line_parser
    runner.dqn_train()
  File "main.py", line 187, in dqn_train
    dqn.initiate_agent(env)
  File "/Users/franzman007/Downloads/neuron_poker-master/agents/agent_dqn.py", line 98, in initiate_agent
    batch_size=batch_size, train_interval=train_interval, enable_double_dqn=enable_double_dqn)
  File "/Users/franzman007/opt/anaconda3/lib/python3.7/site-packages/rl/agents/dqn.py", line 107, in __init__
    if hasattr(model.output, '__len__') and len(model.output) > 1:
  File "/Users/franzman007/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 741, in __len__
    "shape information.".format(self.name))
TypeError: len is not well defined for symbolic Tensors. (dense_4/BiasAdd:0) Please call `x.shape` rather than `len(x)` for shape information.
(base) franzman007:neuron_poker-master franzman007$ 

It ist possible, that my Version of Pyhton is incompatible?

Thank you for your great work

**Comment by dickreuter** [comment]
reverted https://github.com/dickreuter/neuron_poker/pull/23
