### ISSUE TITLE
Illegal moves

### ISSUE THREAD

**Issue by Stroemgren** [dickreuter/neuron_poker#27]
Hi Nicolas.

Cool project! I just got it up and running, testing the DQN agent.

I had problems with the agent keep trying illegal moves. While googling around I found a SA question of yours related to the same problems.

There might be multiple things wrong, but one episode I stumbled over in my logs is a case where the agent wants to make a call or a bet while the legal moves are being limited to check and all in. So the agent is determined to put money in the pot, but is not smart enough to figure that calling or betting would _imply_ an all in. Might it not be better to find a way to accept a call or a bet as a legal move in this instance, to not penalize with negative rewards?

**Comment by dickreuter** [comment]
I think the best way is to add a policy that converts illegal moves to legal ones based on a simple rule. 

But this is not possible in Keras-rl I believe, as it doesn’t seem to allow passing env info into the poliCH, so the only ways I can see is a custom implementation, which I’m currently working on.

**Comment by Stroemgren** [comment]
You think it would bad to just have the environment interpret the agents action as the "closest" legal move? Bets and all ins would be interpreted as calls if stack size is less than the call, folds as checks if no bet is in the pot.

**Comment by dickreuter** [comment]
I think that may be a good short term fix. I pushed some changes that that do this.
