### ISSUE TITLE
Higher / variable number of iterations for equity calculation

### ISSUE THREAD

**Issue by straeter** [dickreuter/neuron_poker#32]
Great work first of all!

The montecarlo simulation works fine and very fast for me.

However, I do not understand why the number of iterations for equity calculation is set to 10 in the main environment (unlike e.g. the montecarlo tests with 5000 iterations):

- it results in a very high variance
- it can be set higher without high cost (especially for the c++ implementation)
- it should be an argument imho
- especially the agent that considers equity should have a good estimate (and maybe recalculate it)

Hope I did not overlook something, otherwise it should be an easy fix

**Comment by dickreuter** [comment]
Can you post a link to the code you're referring to? tx

**Comment by straeter** [comment]
sure:
https://github.com/dickreuter/neuron_poker/blob/master/gym_env/env.py#L269

**Comment by dickreuter** [comment]
Yes I agree, it should be set to around 5000.
