### ISSUE TITLE
Negative remaining stack and wrong size of RAISE_3BB

### ISSUE THREAD

**Issue by dsfdsfgdsa** [dickreuter/neuron_poker#41]
The following log shows that at the moment negative remaining stacks are possible. Also there is a wrong size of Raise3BB. On Pokerstars a raise on 3 BB is for a big blind of 100 a raise on 300.

INFO - Dealer is at position 3
INFO - Player 0 got ['JC', '4D'] and $594
INFO - Player 3 got ['QS', '9C'] and $6
INFO - 
INFO - ===Round: Stage: PREFLOP
INFO - Seat 0 (equity/50/70): Action.SMALL_BLIND - Remaining stack: 593, Round pot: 1, Community pot: 0, player pot: 1
INFO - Seat 3 (Random): Action.BIG_BLIND - Remaining stack: 4, Round pot: 3, Community pot: 0, player pot: 2
INFO - Seat 0 (equity/50/70): Action.CALL - Remaining stack: 592, Round pot: 4, Community pot: 0, player pot: 2
INFO - Seat 3 (Random): Action.RAISE_3BB - Remaining stack: -4, Round pot: 12, Community pot: 0, player pot: 10
INFO - Seat 0 (equity/50/70): Action.FOLD - Remaining stack: 592, Round pot: 12, Community pot: 0, player pot: 2
INFO - Only one player remaining in round
INFO - Player 3 won: Only remaining player in round

I could provida a test and a fix, just let me know.

**Comment by dickreuter** [comment]
merged your tests that are currently failing. Would be great if somebody can try and fix them.
