### ISSUE TITLE
bash: main.py: command not found

### ISSUE THREAD

**Issue by jaimeggb** [dickreuter/neuron_poker#74]
**Describe the bug**
When I type `main.py selfplay random --render` in my terminal, I get `bash: main.py: command not found`

**To Reproduce**
1. Create a virtual environment with `conda create -n neuron_poker python=3.7`
2. Activate it with conda activate neuron_poker, then install all required packages with `pip install -r requirements.txt`
3. Run 6 random players playing against each other: `main.py selfplay random --render`

**Expected behavior**
I expected a 6 player game to begin in the form of text in the terminal or in the form of a GUI in a seperate window 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/90380932/196386985-7478c0a4-813f-4b7f-b616-61f2372b1d22.PNG)

**Comment by jaimeggb** [comment]
Using `python main.py selfplay random --render` instead of just `main.py selfplay random --render` seems to work, but gives a new error:

> AssertionError: The environment must specify an observation space. https://www.gymlibrary.dev/content/environment_creation/

**To Reproduce**
Steps to reproduce the behavior:
1. Create a virtual environment with `conda create -n neuron_poker python=3.7`
2. Activate it with `conda activate neuron_poker`, then install all required packages with `pip install -r requirements.txt`
Run 6 random players playing against each other: `python main.py selfplay random --render`

**Expected behavior**
I expected a 6 player game to begin in the form of text in the terminal or in the form of a GUI in a seperate window

**Screenshots**
![Capture](https://user-images.githubusercontent.com/90380932/196399110-1de4c05b-8d8d-4dd3-b14a-1998dfe5d2cc.PNG)

**Comment by Bonobo791** [comment]
@jaimeggb what did you do to fix this error with the observation space?
