### ISSUE TITLE
Duplicated enum value

### ISSUE THREAD

**Issue by TexHik620953** [dickreuter/neuron_poker#85]
Duplicated enum value in Action enum
./gym_env/enums.py

class Action(Enum):
    """Allowed actions"""
    FOLD = 0
    CHECK = 1
    CALL = 2
    RAISE_3BB = 3              <--------------
    RAISE_HALF_POT = 3    <--------------
    RAISE_POT = 4
    RAISE_2POT = 5
    ALL_IN = 6
    SMALL_BLIND = 7
    BIG_BLIND = 8

**Comment by dickreuter** [comment]
fixed
